services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
      EXEC: 1
      TIMEOUT_CLIENT: 3600 
      TIMEOUT_CONNECT: 30
      TIMEOUT_SERVER: 3600

  crontask:
    build:
      context: .
      dockerfile: .\Dockerfile
    image: crontab:v1.0.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
    depends_on:
      - socket-proxy
